### ISSUE TITLE
Aggregated metrics question

### ISSUE THREAD

**Issue by atroschinetz-rmn** [verisign/storm-graphite#7]
In [this blog post](http://www.michael-noll.com/blog/2013/11/06/sending-metrics-from-storm-to-graphite/#carbon-cache-configuration) you mention metrics like `prefix.HOSTNAME.tuples.received.count` or `m1_rate`, `m5_rate`, etc...

Should we be seeing metrics like this after installing strom-graphite (version 0.1.5-SNAPSHOT)? Or is aggregation now handled by constructing graphite queries, such as:

```
groupByNode(storm.cluster.metrics.*.*.*.*.*.*.*.*.__execute-latency.*, 4, 'sumSeries')
```

Right now we see things like this instead:

![screen shot 2015-03-20 at 2 05 58 pm](https://cloud.githubusercontent.com/assets/7365313/6758968/42eba094-cf0a-11e4-8750-5f639474c69b.png)

**Comment by miguno** [comment]
The metrics (and their paths) in the linked blog post are different -- they use the DropWizard/Coda Hale's Metrics lib for a) generating the metrics in your Storm bolts, and then b) to also send the metrics to Graphite.

storm-graphite is different: the metrics (step (a) above) are generated by the Storm framework behind the scenes, and then (step (b) above) storm-graphite simply sends those pre-generated metrics to Graphite.  (It just a coincidence that storm-graphite uses the Metrics lib to perform this send step because, well, the functionality of talking to Graphite is already provided by that lib.)

Does that help?

**Comment by miguno** [comment]
You can also use carbon-aggregator if you have a need for that -- simply switch the config from carbon-cache's port (default: 2003) to carbon-aggregator's port.

**Comment by atroschinetz-rmn** [comment]
Excellent, that does clear things up!
